=== copierrj/deegree3/deegree-datastores/deegree-tilestores/deegree-tilestore-remotewmts/src/main/resources/META-INF/schemas/datasource/tile/remotewmts/3.2.0/remotewmts.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.deegree.org/datasource/tile/remotewmts" elementFormDefault="qualified"
  xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1">

  <annotation>
    <appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="org.deegree.tile.persistence.remotewmts.jaxb" />
      </jaxb:schemaBindings>
    </appinfo>
  </annotation>

  <element name="RemoteWMTSTileStore">
    <annotation>
      <documentation>TileStore that is backed by a remote WMTS instance.</documentation>
      <appinfo>
        <jaxb:class name="RemoteWMTSTileStoreJAXB" />
      </appinfo>
    </annotation>
    <complexType>
      <sequence>
        <element name="RemoteWMTSId" type="string">
          <annotation>
            <documentation>Id of the remote WMTS to connect to</documentation>
          </annotation>
        </element>
        <element name="TileDataSet" maxOccurs="unbounded">
          <complexType>
            <sequence>
              <element name="Identifier" type="string">
                <annotation>
                  <documentation>Identifier for the tile data set</documentation>
                </annotation>
              </element>
              <element name="OutputFormat" type="string">
                <annotation>
                  <documentation>Mime type of the desired output format</documentation>
                </annotation>
              </element>
              <element name="RequestParams">
                <annotation>
                  <documentation>WMTS request parameters</documentation>
                </annotation>
                <complexType>
                  <sequence>
                    <element name="Layer" type="string">
                      <annotation>
                        <documentation>Layer name</documentation>
                      </annotation>
                    </element>
                    <element name="Style" type="string">
                      <annotation>
                        <documentation>Style identifier</documentation>
                      </annotation>
                    </element>
                    <element name="Format" type="string">
                      <annotation>
                        <documentation>Image format</documentation>
                      </annotation>
                    </element>
                    <element name="TileMatrixSet" type="string">
                      <annotation>
                        <documentation>Identifier of the remote tile matrix set</documentation>
                      </annotation>
                    </element>
                  </sequence>
                </complexType>
              </element>
            </sequence>
          </complexType>
        </element>
      </sequence>
      <attribute name="configVersion" use="required" fixed="3.2.0" />
    </complexType>
  </element>

</schema>

=== copierrj/deegree3/deegree-datastores/deegree-tilestores/deegree-tilestore-remotewmts/src/main/resources/META-INF/schemas/datasource/tile/remotewmts/3.2.0/example.xml
<?xml version="1.0"?>
<RemoteWMTSTileStore xmlns="http://www.deegree.org/datasource/tile/remotewmts" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.deegree.org/datasource/tile/remotewmts remotewmts.xsd" configVersion="3.2.0">

  <!-- [1] Id of the remote WMTS to connect to -->
  <RemoteWMTSId>wms1</RemoteWMTSId>

  <TileDataSet>
    <!-- [1] Identifier for the tile data set -->
    <Identifier>satellite</Identifier>
    <!-- [1] Mime type of the desired output format -->
    <OutputFormat>image/png</OutputFormat>
    <!-- [1] WMTS request parameters -->
    <RequestParams>
      <!-- [1] Layer name -->
      <Layer>SatelliteProvo</Layer>
      <!-- [1] Style identifier -->
      <Style>default</Style>
      <!-- [1] Image format -->
      <Format>image/png</Format>
      <!-- [1] Identifier of the remote tile matrix set -->
      <TileMatrixSet>EPSG:4326</TileMatrixSet>
    </RequestParams>
  </TileDataSet>

</RemoteWMTSTileStore>
